service: Psardermkor-Node
provider:
  name: aws
  runtime: nodejs10.x
functions:
  auth:
    handler: functions/Auth/index.handler
    events:
      - http:
          path: api/auth
          method: post
          documentation: '${self:custom.endpoints.auth}'
  auth/login:
    handler: functions/Login/index.handler
    events:
      - http:
          path: api/auth/login
          method: post
  user/signInUp:
    handler: functions/Users/signInUp.handler
    events:
      - http:
          path: api/user/auth
          method: post
  user/request:
    handler: functions/Users/request.handler
    events:
      - http:
          path: api/user/request
          method: post
  notification:
    handler: functions/Notification/sendNotification.handler
    events:
      - http:
          path: api/notify
          method: post
plugins:
  - serverless-offline
